theme: jekyll-theme-architect
name: Emily Bedford
title:  Emilys Funtastical Facts!

baseurl: ""

future: true

url: http://www.emily-bedford.com

permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - CNAME
    - README.md
    - cacert.pem