theme: jekyll-theme-architect
name: Emily Bedford
title:  Emilys Funtastical Facts!

baseurl: ""

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.emily-bedford.com

permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - CNAME
    - README.md
    - cacert.pem